name: CI

on: [push]

jobs:
  run:
    name: Test plugin
    timeout-minutes: 15
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Install dependancies
        run: |
        python -m pip install --upgrade pip
        pip install multiqc flake8 pytest
      - name: Run flake8
        run: |
          flake8 multiqc_blr/ tests/
      - name: Run tests
        run: |
          python setup.py install
          pytest -v tests/test.py
